#!/bin/bash

set -e

SOPS_FILE=".env.encrypted.yaml"
ENV_FILE=".env.yaml"
AGE_KEY=$(grep "public key" ~/.secrets/sops/keys.txt | awk '{print $NF}')

if [ -f "$ENV_FILE" ]; then
    echo "encrypting $ENV_FILE to $SOPS_FILE"
    sops --encrypt --age "$AGE_KEY" "$ENV_FILE" > "$SOPS_FILE"
    git add "$SOPS_FILE"
    echo "encrypted $ENV_FILE to $SOPS_FILE"
fi