services:
  crafty:
    container_name: mc
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Asia/Calcutta
    ports:
      - "8443:8443"
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - ${VOLUME}/backups:/crafty/backups
      - ${VOLUME}/logs:/crafty/logs
      - ${VOLUME}/servers:/crafty/servers
      - ${VOLUME}/config:/crafty/app/config
      - ${VOLUME}/import:/crafty/import
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crafty.rule=Host(`mc.adityajyoti.com`)"
      - "traefik.http.routers.crafty.entrypoints=https"
      - "traefik.http.routers.crafty.tls=true"
      - "traefik.http.routers.crafty.tls.certresolver=letsencrypt"
      - "traefik.http.services.crafty.loadbalancer.server.port=8443"
      - "traefik.http.services.crafty.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
