services:
  collabora:
    image: collabora/code
    container_name: docs
    ports:
      - "${PORT}:9980"
    restart: unless-stopped
    # volumes:
    #   - /var/container/collabora/etc/coolwsd/:/etc/coolwsd/:rw
    environment:
      - domain=${DOMAIN}
      - username=${USERNAME}
      - password=${PASSWORD}
      - dictionaries=en_US
      - TZ=Asia/Kolkata
