services:
  flatnotes:
    container_name: markdown
    image: dullage/flatnotes:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: ${USERNAME}
      FLATNOTES_PASSWORD: ${PASSWORD}
      FLATNOTES_SECRET_KEY: ${SECRET_KEY}
    volumes:
      - "${NOTES_DIR}:/data"
      - "${VOLUME}/index:/data/.flatnotes"
    ports:
      - "${PORT}:8080"
    labels:
      - "traefik.enable=true"
