services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: caldav
    ports:
      - "${CALDAV_PORT}:5232"
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ${CALDAV_VOLUME}/data:/data
    labels:
      - "traefik.enable=true"

  agendav:
    container_name: calendar
    image: ghcr.io/nagimov/agendav-docker:latest
    environment:
      - AGENDAV_SERVER_NAME={AGENDAV_SERVER_NAME}
      - AGENDAV_TITLE=Calendar
      - AGENDAV_FOOTER=Hosted for Aditya Jyoti via Escanor
      - AGENDAV_ENC_KEY={AGENDAV_ENC_KEY}
      - AGENDAV_CALDAV_SERVER={AGENDAV_CALDAV_SERVER}
      - AGENDAV_CALDAV_PUBLIC_URL={AGENDAV_PUBLIC_URL}
      - AGENDAV_TIMEZONE=Asia/Kolkata
      - AGENDAV_LANG=en
      - AGENDAV_LOG_DIR=/app/log
    ports:
      - "${AGENDAV_PORT}:8080"
    volumes:
      - ${AGENDAV_VOLUME}/data:/app/data
      - ${AGENDAV_VOLUME}/log:/app/log
      - ${AGENDAV_VOLUME}/temp:/app/temp
    command: sh -c "chown -R www-data:www-data /app/log && chmod -R 775 /app/log && apache2-foreground"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
