services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: draw
    restart: unless-stopped
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=http://excalidraw-room:3001
      - VITE_APP_BACKEND_V2_POST_URL=http://excalidraw-room:3001
    depends_on:
      - excalidraw-room
    labels:
      - "traefik.enable=true"

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    container_name: excalidraw-room
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/excalidraw
      - ALLOWED_ORIGINS=https://draw.adityajyoti.com
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: excalidraw-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: excalidraw
    volumes:
      - ${VOLUME}:/var/lib/postgresql/data
