services:
  calibre-web-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: books
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: en
      USE_BOOK_TITLE: true
      TZ: Asia/Calcutta
      APP_ENV: prod
      UID: 1000
      GID: 100
    restart: unless-stopped
    volumes:
      - ${BOOK_VOLUME}:/cwa-book-ingest
    labels:
      - "traefik.enable=true"

  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:preview
    container_name: manga
    environment:
      - TZ=Asia/Calcutta
      - DOWNLOAD_AS_CBZ=true
      - EXTENSION_REPOS=["https://raw.githubusercontent.com/ThePBone/tachiyomi-extensions-revived/repo/index.min.json"]
    user: 1000:1000
    restart: on-failure:3
    volumes:
      - ${SUWAYOMI_CONFIG}:/home/suwayomi/.local/share/Tachidesk
    labels:
      - "traefik.enable=true"
