services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${VERSION:-release}
    volumes:
      - ${STORAGE_BOX:?}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORT:?}:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`${DOMAIN:?}`)

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${VERSION:-release}
    volumes:
      - ${DATA_STORAGE:?}/model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:5f6a838e4e44c8e0e019d0ebfe3ee8952b69afc2809b2c25f7b0119641978e91
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DATA_STORAGE:?}/pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
