services:
  agendav:
    container_name: calendar
    image: ghcr.io/nagimov/agendav-docker:latest
    environment:
      - AGENDAV_SERVER_NAME=${SERVER_NAME}
      - AGENDAV_TITLE=Calendar
      - AGENDAV_FOOTER=Hosted for Aditya Jyoti via Escanor
      - AGENDAV_ENC_KEY=${ENC_KEY}
      - AGENDAV_CALDAV_SERVER=${CALDAV_SERVER}
      - AGENDAV_CALDAV_PUBLIC_URL=${PUBLIC_URL}
      - AGENDAV_TIMEZONE=Asia/Kolkata
      - AGENDAV_LANG=en
      - AGENDAV_LOG_DIR=/app/log
    ports:
      - "${PORT}:8080"
    volumes:
      - ${VOLUME}/data:/app/data:rw
      - ${VOLUME}/log:/app/log:rw
      - ${VOLUME}/temp:/app/temp:rw
    restart: unless-stopped
    command: sh -c "chown -R www-data:www-data /var/www/agendav/web && chmod -R 775 /var/www/agendav/web && apache2-foreground"
    labels:
      - "traefik.enable=true"
