services:
  cryptpad:
    image: "cryptpad/cryptpad:version-2024.12.0"
    hostname: cryptpad
    container_name: docs

    environment:
      - CPAD_MAIN_DOMAIN=${MAIN_DOMAIN}
      - CPAD_SANDBOX_DOMAIN=${SANDBOX_DOMAIN}
      - CPAD_CONF=/cryptpad/config/config.js
      - CPAD_INSTALL_ONLYOFFICE=yes

    volumes:
      - ${VOLUME}/blob:/blob
      - ${VOLUME}/block:/block
      - ${VOLUME}/customize:/customize
      - ${VOLUME}/data:/data
      - ${VOLUME}/files:/datastore
      - ${VOLUME}/onlyoffice-dist:/cryptpad/www/common/onlyoffice/dist
      - ${VOLUME}/onlyoffice-conf:/cryptpad/onlyoffice-conf
      - ${VOLUME}/config.js:/cryptpad/config/config.js

    ports:
      - "${MAIN_PORT}:3000"
      - "${SUB_PORT}:3003"

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.docs.loadbalancer.server.port=${MAIN_PORT}"