services:
  komga:
    container_name: read
    image: gotson/komga
    volumes:
      - type: bind
        source: ${VOLUME}
        target: /config
      - type: bind
        source: ${MANGA_DOWNLOAD_PATH}
        target: /manga
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    user: "1000:1000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
