services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver
    container_name: docs

    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq

    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - AMQP_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@onlyoffice-rabbitmq

    #   - JWT_ENABLED=${JWT_ENABLED:-false}
    #   - JWT_SECRET=${JWT_SECRET:-changeme}
    #   - JWT_HEADER=${JWT_HEADER:-Authorization}
    #   - JWT_IN_BODY=${JWT_IN_BODY:-true}

    # ports:
    #   - "${HTTP_PORT:-80}:80"
    #   - "${HTTPS_PORT:-443}:443"

    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
      - ${VOLUME}/data:/var/www/onlyoffice/Data
      - ${VOLUME}/logs:/var/log/onlyoffice
      - ${VOLUME}/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - ${VOLUME}/public:/var/www/onlyoffice/documentserver-example/public/files
      - ${VOLUME}/fonts:/usr/share/fonts

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - "5672"

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:12
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - "5432"
    volumes:
      - ${VOLUME}/db:/var/lib/postgresql
