services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - onlyoffice

    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ${VOLUME}/config/mysql/conf.d:/etc/mysql/conf.d
      - ${VOLUME}/config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${VOLUME}/mysql_data:/var/lib/mysql

  onlyoffice-community-server:
    container_name: docs
    image: onlyoffice/communityserver:12.6.0.1900
    depends_on:
      - onlyoffice-mysql-server
      - onlyoffice-document-server
      - onlyoffice-elasticsearch

    environment:
      - ONLYOFFICE_CORE_MACHINEKEY=${CORE_SECRET}

      - CONTROL_PANEL_PORT_80_TCP=80
      - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel

      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
      - DOCUMENT_SERVER_JWT_ENABLED=true
      - DOCUMENT_SERVER_JWT_SECRET=${JWT_SECRET}
      - DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt

      - MYSQL_SERVER_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_SERVER_DB_NAME=onlyoffice
      - MYSQL_SERVER_HOST=onlyoffice-mysql-server
      - MYSQL_SERVER_USER=${DB_USER}
      - MYSQL_SERVER_PASS=${DB_PASSWORD}

      - ELASTICSEARCH_SERVER_HOST=onlyoffice-elasticsearch
      - ELASTICSEARCH_SERVER_HTTPPORT=9200

    networks:
      - onlyoffice

    ports:
      - "${PORT_80}:80"
      - "${PORT_443}:443"
      - "${PORT_5222}:5222"

    stdin_open: true
    tty: true
    restart: always
    privileged: true
    cgroup: host
    volumes:
      - ${VOLUME}/community_data:/var/www/onlyoffice/Data
      - ${VOLUME}/community_log:/var/log/onlyoffice
      - ${VOLUME}/community_letsencrypt:/etc/letsencrypt
      - ${VOLUME}/document_data:/var/www/onlyoffice/DocumentServerData
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${VOLUME}/certs:/var/www/onlyoffice/Data/certs

    labels:
      - "traefik.enable=true"

  onlyoffice-elasticsearch:
    image: onlyoffice/elasticsearch:7.16.3
    container_name: onlyoffice-elasticsearch
    restart: always

    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      - "indices.fielddata.cache.size=30%"
      - "indices.memory.index_buffer_size=30%"
      - "ingest.geoip.downloader.enabled=false"

    networks:
      - onlyoffice
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ${VOLUME}/es_data:/usr/share/elasticsearch/data

    expose:
      - "9200"
      - "9300"

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:8.1
    stdin_open: true
    tty: true
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HEADER=AuthorizationJwt
    networks:
      - onlyoffice
    expose:
      - "80"
      - "443"

    volumes:
      - ${VOLUME}/document_data:/var/www/onlyoffice/Data
      - ${VOLUME}/document_log:/var/log/onlyoffice
      - ${VOLUME}/document_fonts:/usr/share/fonts/truetype/custom
      - ${VOLUME}/document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten

networks:
  onlyoffice:
    driver: "bridge"
