services:
  homarr:
    container_name: home
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME}/configs:/app/data/configs
      - ${VOLUME}/icons:/app/public/icons
      - ${VOLUME}/data:/data
    labels:
      - "traefik.enable=true"
