services:
  photoview-prepare:
    image: photoview/photoview:2
    hostname: photoview-prepare
    container_name: photoview-prepare
    user: root
    entrypoint: []
    command: /bin/bash -c "sleep 1 && chown -R photoview:photoview /home/photoview/media-cache"
    cap_add:
      - CHOWN
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${HOST_PHOTOVIEW_LOCATION:?}/storage:/home/photoview/media-cache"

  photoview:
    image: photoview/photoview:2
    hostname: photoview
    container_name: photoview
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - ${PORT:?}:80
    depends_on:
      photoview-prepare:
        condition: service_completed_successfully
      mariadb:
        condition: service_healthy
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOVIEW_DATABASE_DRIVER: mysql
      PHOTOVIEW_MYSQL_URL: "${MARIADB_USER:?}:${MARIADB_PASSWORD:?}@tcp(photoview-mariadb)/${MARIADB_DATABASE:?}"
      PHOTOVIEW_LISTEN_IP: "0.0.0.0"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${HOST_PHOTOVIEW_LOCATION:?}/storage:/home/photoview/media-cache"
      - "${HOST_PHOTOVIEW_MEDIA_ROOT:?}:/photos:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.photoview.rule=Host(`${DOMAIN:?}`)

  mariadb:
    image: mariadb:lts
    hostname: photoview-mariadb
    container_name: photoview-mariadb
    restart: unless-stopped
    stop_grace_period: 5s
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DATABASE: ${MARIADB_DATABASE:?}
      MARIADB_USER: ${MARIADB_USER:?}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:?}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${HOST_PHOTOVIEW_LOCATION}/database/mariadb:/var/lib/mysql"
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 3m
