services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: acads
    user: 1000:1000
    volumes:
      - ${DATA}:/srv
      - ${VOLUME}/filebrowser.db:/database.db
      - ${VOLUME}/filebrowser.json:/.filebrowser.json
    restart: always
    ports:
      - ${PORT}:80
    labels:
      - "traefik.enable=true"
