version: "3"
services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${VOLUME}/db:/data/db

  lynx:
    container_name: url-shortener
    image: jackbailey/lynx:1
    restart: always
    depends_on:
      - db
    volumes:
      - ${VOLUME}/backup:/app/backups
    environment:
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - URL_LENGTH=8
      - URL_SET=standard
      - URL_ONLY_UNIQUE=false
      - HOME_REDIRECT=/dash/overview
      - FORCE_FRONTEND_REDIRECT=false
      - ENABLE_REGISTRATION=false
      - DOMAIN=http://${DOMAIN}
      - DEMO=false
      - USE_HTTPS=true
      - CORS=*
      - BACKUP=true
      - BACKUP_SCHEDULE=0 0 * * *
      - BACKUP_COUNT=5

      - DB_HOST=db
      - DB_PORT=27017
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lynx.rule=Host(`${DOMAIN}`)"
