services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-personal
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - ${PORT:?}:8000
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: ${DB_USER:-paperless}
      PAPERLESS_DBPASS: ${DB_PASSWORD:-paperless}
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://${DOMAIN:?}
      PAPERLESS_USE_X_FORWARDED_HOST: true
    volumes:
      - ${STORAGE_BOX:?}/data:/usr/src/paperless/data
      - ${STORAGE_BOX:?}/media:/usr/src/paperless/media
      - ${DATA_STORAGE:?}/export:/usr/src/paperless/export
      - ${DATA_STORAGE:?}/consume:/usr/src/paperless/consume
    labels:
      - traefik.enable=true
      - traefik.http.routers.paperless-personal.rule=Host(`${DOMAIN:?}`)

  db:
    image: postgres:17
    container_name: paperless-personal-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: ${DB_USER:-paperless}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-paperless}
    volumes:
      - ${DATA_STORAGE:?}/pgdata:/var/lib/postgresql/data

  broker:
    image: redis:8
    container_name: paperless-personal-broker
    restart: unless-stopped
    volumes:
      - ${DATA_STORAGE:?}/redisdata:/data
