name: sync with vps
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Navigate to project directory and pull changes
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main

            # Decrypt environment file
            sops --decrypt .env.encrypted.yaml > .env.yaml

            # Process each service
            cd services

            for dir in */; do
              if [ -f "${dir}docker-compose.yml" ]; then
                echo "Deploying service in: $dir"
                
                # Extract environment variables for this service
                SERVICE_ENV=$(yq -r ".${dir%/} | to_entries | .[] | \"\(.key)=\(.value)\"" ../.env.yaml)
                
                # Export environment variables
                eval "$(echo "$SERVICE_ENV" | sed 's/^/export /')"
                
                # Run docker-compose
                cd "$dir"
                docker-compose up -d
                cd ..
              fi
            done
