name: sync with vps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo, ie, get all that is present inside the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install necessary dependencies (sops, ssh-agent, etc.)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sops sshpass

      # Step 3: Decrypt the .env.encrypted.yaml file using SOPS
      - name: Decrypt .env.encrypted.yaml
        run: |
          SOPS_AGE_KEY_FILE=${{ secrets.AGE_KEY }} sops --decrypt .env.encrypted.yaml > .env.yaml

      # Step 3: Connect to the VPS using SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Move to the project directory
            cd ${{ secrets.PROJECT_PATH }}

            # Pull the latest changes from the main branch
            git pull origin main 

            # Decrypt the .env.encrypted.yaml file using SOPS
            SOPS_AGE_KEY_FILE=${{ secrets.AGE_KEY }} sops --decrypt .env.encrypted.yaml > .env.yaml

            # Move into services directory 
            cd services 

            # Run docker compose for each service
            for dir in *; do
              if [ -d "$dir" ] && [ -f "$dir/docker-compose.yml" ]; then
                echo "Deploying service in directory: $dir"

                # Get all decrypted environment variables
                SERVICE_ENV=$(yq -r ".${dir} | to_entries | .[] | \"\(.key)=\(.value)\"" ../.env.yaml)

                # Get all decrypted environment variables and export them into one line
                while IFS= read -r line; do
                  export "$line"
                done <<< "$SERVICE_ENV"

                # Move into the service directory and run docker-compose
                cd "$dir"
                docker-compose up -d
                cd -
              fi
            done
